### ISSUE TITLE
Problem with XPath

### ISSUE THREAD

**Issue by cheiftain** [code4craft/xsoup#23]
Hi, i'm using XSoup With XPath query //div[@class="sp"], but i got this match result: `<div` class="logo `sp">北邮人论坛手机版</div>` Is it a bug?

**Comment by code4craft** [comment]
这个是故意做的适配，因为对于CSS来说这其实是两个class的聚合，而不是单独的一个"logo sp"。

**Comment by cheiftain** [comment]
原来是这样，明白了，谢谢！
